package constant;

public enum ErrorCode {
    //TODO: 같은 곳으로 이동할 때 예외 다르게 errorCode
    INVALID_INPUT,
    INVALID_STATUS,
    INVALID_COMMAND,
    INVALID_POSITION,
    INVALID_PAWN_MOVEMENT,
    INVALID_KING_MOVEMENT,
    INVALID_BISHOP_MOVEMENT,
    INVALID_KNIGHT_MOVEMENT,
    INVALID_QUEEN_MOVEMENT,
    INVALID_ROOK_MOVEMENT,
    PIECE_EXIST_IN_ROUTE,
    OWN_PIECE_EXIST_POSITION,
    PIECE_DOES_NOT_EXIST_POSITION,
    INVALID_CAMP_PIECE,
    KING_DEAD,
    CONNECTION,
    FAIL_SAVE,
    FAIL_FIND,
    FAIL_DELETE,
    NO_MESSAGE
}
